### ISSUE TITLE
NoClassDefFound

### ISSUE THREAD

**Issue by PaulWoitaschek** [andrewoma/kotlin-script#8]
When executing the sample I immediately get an exception using Kotlin 1.0.5 and Arch Linux

```kotlin
#!/usr/bin/env kotlins

println("Hello from Kotlin! args.size=${args.size}")
```

```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at MainKt.main(main.kt)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by andrewoma** [comment]
Sorry it's taken me so long to look at this. I just tried 1.0.5 locally and it seems to work using the distribution from https://github.com/JetBrains/kotlin/releases/download/v1.0.5/kotlin-compiler-1.0.5.zip.

The error looks like kotlin runtime .jar isn't included.

Maybe the arch linux packaging isn't in the standard layout. i.e. this line in script:

TOOL_CLASSPATH="$KOTLIN_HOME"/lib/kotlin-runtime.jar

Cheers,
Andrew
